services:
  backend:
    env_file:
      - .env.production
    environment:
      DOMAIN_NAME: partycash.me

  frontend:
    build:
      context: ./PartyCashFE
      args:
        CONFIG_FILE: production.config.ts

  reverse-proxy:
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
