services:
  backend:
    env_file:
      - .env.staging
    environment:
      DOMAIN_NAME: staging.partycash.me

  frontend:
    build:
      context: ./PartyCashFE
      args:
        CONFIG_FILE: staging.config.ts

  reverse-proxy:
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf:ro
