services:
  db:
    image: postgres:14-alpine
    container_name: partybudget_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: partybudget
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - partycash_network

  backend:
    build:
      context: ./PartyCashBE
      dockerfile: Dockerfile
    container_name: partybudget_backend
    environment:
      DB_USER: admin
      DB_HOST: db          # Nome del servizio del database
      DB_NAME: partybudget
      DB_PASSWORD: admin
      DB_PORT: 5432
      PORT: 3000
      JWT_SECRET: your_secret_key
      DOMAIN_NAME: staging.partycash.me

    ports:
      - "3000:3000"
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro # Mount the certificates
    depends_on:
      - db
    networks:
      - partycash_network

  frontend:
    build:
      context: ./PartyCashFE
      dockerfile: Dockerfile
    container_name: partycash_frontend
    restart: always
    ports:
      - "5173:80"    # Host porta 5173 -> Container porta 80 (per test diretto esterno)
    depends_on:
      - backend
    networks:
      - partycash_network



  reverse-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - frontend
    networks:
    - partycash_network

volumes:
  db_data:

networks:
  partycash_network:
