services:
  db:
    image: postgres:14-alpine
    container_name: partybudget_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: partybudget
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - partycash_network

  backend:
    build:
      context: ./PartyCashBE
      dockerfile: Dockerfile
    container_name: partybudget_backend
    environment:
      DB_USER: admin
      DB_HOST: db          # Nome del servizio del database
      DB_NAME: partybudget
      DB_PASSWORD: admin
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - partycash_network

  frontend:
    build:
      context: ./PartyCashFE
      dockerfile: Dockerfile
    container_name: partycash_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - partycash_network
volumes:
  db_data:

networks:
  partycash_network:
