name: Deploy to EC2

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/partycashAPP
            
            # Determina il branch e l'override file in base al branch della push
            if [ "${GITHUB_REF##*/}" = "main" ]; then
              echo "Deploying production..."
              branch="main"
              compose_file="docker-compose.production.yml"
            else
              echo "Deploying staging..."
              branch="staging"
              compose_file="docker-compose.staging.yml"
            fi
            
            # Esegui il pull dal branch corretto
            git pull origin $branch
            
            # Usa il file di override corretto
            docker compose -f docker-compose.yml -f $compose_file down
            docker compose -f docker-compose.yml -f $compose_file up -d --build
